batch_size: 64
lr: 0.00001
pin_memory: True
num_workers: 2
base_path: datasets/CrisisMMD_v2.0/CrisisMMD_v2.0/
train_data_path: crisismmd_datasplit_all/task_humanitarian_text_img_train.tsv
test_data_path: crisismmd_datasplit_all/task_humanitarian_text_img_test.tsv
SEED: 42
gpu: 6
freq: 3
model_name: lstmcnn2
cnn_type: resnet
nclass: 5
img_size:
        - 512
        - 256
augment: False
return_logs: True
saved_path: saved_models/LSTM_CNN2.pt
layer: CNN_layer4_1_conv2
analysis: gradcampp
gradcam_saved_path: gradcam_imgs/gradcampp_lstmcnn2