batch_size: 32
lr: 0.001
pin_memory: True
num_workers: 2
dataset_path: datasets/cifar10
SEED: 42
gpu: 6
momentum: 0.9
model_name: pyramidnet
nclass: 10
alpha: 48
depth: 32
dataset: cifar10
epochs: 30
augment: True
return_logs: False
load: True
roc_save_path: roc_folder/pyr_augment.svg
saved_path: saved_models/pyramidnet_augment.pt
