batch_size: 32
lr: 0.001
pin_memory: True
num_workers: 2
dataset_path: /DATA/sharma59/Know_distil/datafreekd/scripts/svhndata
SEED: 42
gpu: 1
momentum: 0.9
nclass: 10
epochs: 50
return_logs: False
model_saved_path: /DATA/sharma59/sem8assn/sem-8-assn/DAI/saved_models/que2_shufflenet.pt
model_name: shufflenet
load: True
attack: pgd
epsilon:
    - 0.01
    - 0.02
    - 0.05
    - 0.1
    - 0.2
    - 0.5
# epsilon: 0.01
save_path: /DATA/sharma59/sem8assn/DAI/assn_plots/que2_shufflenet.png